// Class hierarchy and module names of the kernel API (lib/c3d/c3d.d.ts).
// Anything not implemented by the OCCT kernel is stubbed from this list so that
// `instanceof` checks keep working and unimplemented calls fail with a clear message.

export const classes: [string, string | null][] = [
    ["RefItem", null],
    ["Function", null],
    ["CubicFunction", "Function"],
    ["SpaceItem", "RefItem"],
    ["ControlData3D", null],
    ["Creator", "RefItem"],
    ["Transactions", null],
    ["Model", "RefItem"],
    ["Item", "SpaceItem"],
    ["TopItem", "RefItem"],
    ["Path", null],
    ["Rect", null],
    ["Cube", null],
    ["BooleanFlags", null],
    ["SurfaceOffsetCurveParams", null],
    ["Surface", "SpaceItem"],
    ["Solid", "Item"],
    ["Assembly", "Item"],
    ["RegTransform", null],
    ["PlaneItem", "RefItem"],
    ["Curve", "PlaneItem"],
    ["PolyCurve", "Curve"],
    ["Hermit", "PolyCurve"],
    ["CubicSpline", "PolyCurve"],
    ["Polyline", "PolyCurve"],
    ["Contour", "Curve"],
    ["ContourWithBreaks", "Contour"],
    ["PlanarCheckParams", null],
    ["Rect1D", null],
    ["Curve3D", "SpaceItem"],
    ["Rect2D", null],
    ["TrimmedCurve3D", "Curve3D"],
    ["TrimmedCurve", "Curve"],
    ["ReparamCurve3D", "Curve3D"],
    ["ReparamCurve", "Curve"],
    ["BridgeCurve3D", "Curve3D"],
    ["OffsetCurve3D", "Curve3D"],
    ["OffsetCurve", "Curve"],
    ["SurfaceCurve", "Curve3D"],
    ["Spiral", "Curve3D"],
    ["ConeSpiral", "Spiral"],
    ["CurveSpiral", "Spiral"],
    ["PlaneCurve", "Curve3D"],
    ["Contour3D", "Curve3D"],
    ["Plane", "Surface"],
    ["CartPoint", null],
    ["CartPoint3D", null],
    ["ElementarySurface", "Surface"],
    ["TorusSurface", "ElementarySurface"],
    ["FaceShell", "TopItem"],
    ["EdgeFacesIndexes", null],
    ["ShellHistory", null],
    ["ElementarySolid", "Creator"],
    ["SphereSurface", "ElementarySurface"],
    ["Instance", "Item"],
    ["SpaceInstance", "Item"],
    ["PlaneInstance", "Item"],
    ["Region", "PlaneItem"],
    ["Direction", null],
    ["Line", "Curve"],
    ["LineSegment", "Curve"],
    ["Line3D", "Curve3D"],
    ["Vector", null],
    ["Vector3D", null],
    ["Axis3D", null],
    ["Placement", null],
    ["Placement3D", null],
    ["FormNote", null],
    ["FloatAxis3D", null],
    ["FloatPoint3D", null],
    ["Mesh", "Item"],
    ["RegDuplicate", null],
    ["AutoRegDuplicate", null],
    ["NameMaker", "RefItem"],
    ["SNameMaker", "NameMaker"],
    ["StepData", null],
    ["Name", null],
    ["Matrix", null],
    ["Homogeneous3D", null],
    ["Matrix3D", null],
    ["TopologyItem", "TopItem"],
    ["Edge", "TopologyItem"],
    ["SurfaceIntersectionCurve", "Curve3D"],
    ["CurveEdge", "Edge"],
    ["ContourOnSurface", "Curve3D"],
    ["ContourOnPlane", "ContourOnSurface"],
    ["OrientedEdge", null],
    ["Loop", "TopItem"],
    ["Face", "TopologyItem"],
    ["Vertex", "TopologyItem"],
    ["ModifyValues", null],
    ["TransformValues", null],
    ["SmoothValues", null],
    ["ShellCuttingParams", null],
    ["EdgeFunction", null],
    ["FunctionFactory", null],
    ["CharacterCurve", "Curve"],
    ["CharacterCurve3D", "Curve3D"],
    ["Arc3D", "Curve3D"],
    ["Arc", "Curve"],
    ["PolyCurve3D", "Curve3D"],
    ["Polyline3D", "PolyCurve3D"],
    ["Bezier3D", "PolyCurve3D"],
    ["Bezier", "PolyCurve"],
    ["CubicSpline3D", "PolyCurve3D"],
    ["Hermit3D", "PolyCurve3D"],
    ["Nurbs3D", "PolyCurve3D"],
    ["Nurbs", "PolyCurve"],
    ["LineSegment3D", "Curve3D"],
    ["PointFrame", "Item"],
    ["EdgeSequence", null],
    ["MergingFlags", null],
    ["SweptValues", null],
    ["LoftedValues", "SweptValues"],
    ["EvolutionValues", "SweptValues"],
    ["SweptSide", null],
    ["SweptValuesAndSides", "SweptValues"],
    ["RevolutionValues", "SweptValuesAndSides"],
    ["ExtrusionValues", "SweptValuesAndSides"],
    ["SweptData", null],
    ["RegionBooleanParams", null],
    ["SmoothSolid", "Creator"],
    ["SimpleCreator", "Creator"],
    ["CurveSweptSolid", "Creator"],
    ["CurveExtrusionSolid", "CurveSweptSolid"],
    ["CurveRevolutionSolid", "CurveSweptSolid"],
    ["CurveEvolutionSolid", "CurveSweptSolid"],
    ["CurveLoftedSolid", "CurveSweptSolid"],
    ["BooleanSolid", "Creator"],
    ["CuttingSolid", "Creator"],
    ["SymmetrySolid", "Creator"],
    ["HoleSolid", "CurveSweptSolid"],
    ["ChamferSolid", "SmoothSolid"],
    ["FilletSolid", "SmoothSolid"],
    ["ShellSolid", "Creator"],
    ["DraftSolid", "Creator"],
    ["RibSolid", "Creator"],
    ["SplitShell", "Creator"],
    ["NurbsBlockSolid", "Creator"],
    ["FaceModifiedSolid", "Creator"],
    ["ModifiedNurbsItem", "Creator"],
    ["TransformedSolid", "Creator"],
    ["ThinShellCreator", "Creator"],
    ["UnionSolid", "Creator"],
    ["DetachSolid", "Creator"],
    ["DuplicationSolid", "Creator"],
    ["ReverseCreator", "Creator"],
    ["TransformationMaker", "Creator"],
    ["ExtensionShell", "Creator"],
    ["Graph", null],
    ["CrossPoint", null],
    ["PointOnCurve", null],
    ["WireFrame", null],
    ["Primitive", "RefItem"],
    ["Grid", "Primitive"],
    ["Polygon3D", "Primitive"],
    ["ConvConvertorProperty3D", null],
    ["C3dModelDocument", null],
    ["C3DPmiToItem", null],
    ["Multiline", "PlaneItem"],
    ["VertexOfMultilineInfo", null],
    ["MLTipParams", null],
    ["ShellsIntersectionData", null],
    ["ShellsDistanceData", null],
    ["SpatialOffsetCurveParams", null],
    ["DuplicationValues", null],
    ["DuplicationMeshValues", "DuplicationValues"],
    ["ExtensionValues", null],
    ["HoleValues", null],
    ["SlotValues", "HoleValues"],
    ["SolidDuplicate", null],
    ["SolidPool", null],
];

export const modules: string[] = [
    "Action",
    "ActionSurface",
    "ActionSurfaceCurve",
    "ActionSolid",
    "ActionPoint",
    "ActionDirect",
    "ActionPhantom",
    "ActionCurve",
    "ActionCurve3D",
    "ActionRegion",
    "ActionMesh",
    "ActionShell",
    "Mutex",
    "ContourGraph",
    "CurveEnvelope",
    "CurveTangent",
    "CurveUtil",
    "MeshGrid",
    "Writer",
    "Registrator",
    "TriFace",
    "Conversion",
];
